.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 11/30/13               \" DATE 
.Dt imagecrunch 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm imagecrunch,
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd Scale, crop, autorotate and convert images to many sizes with a single command
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Ar inputfile.gif, .jpg or .png              \" [file]
.Op Fl crop Ar x y w h (use only once)        \" [-a path]
.Op Fl size Ar w h (use many times)         \" [-a path]
.Op Fl write Ar outputfile.gif, .jpg or .png (use many times)         \" [-a path]
.Sh DESCRIPTION          \" Section Header - required - don't modify
Examples:

imagecrunch image.png -size 50 50 -write icon.png -size 200 200 -write small.png
imagecrunch groupphoto.jpg -crop 200 200 300 300 -write bob.jpg

Images are NEVER distorted and NEVER enlarged. The width and height you specify to -size specify a box the output image must fit into; if the original is big enough, the output image will match one of those dimensions and scale the other without exceeding it.

You may repeat -size and -write many times. The -crop option may only be used once per invocation and is in the coordinates of the orginal image.

GIF, JPEG and PNG files are supported. Output filenames must end in .gif, .jpg or .png.

This tool renders natively with Quartz on MacOS, which is why it is so tiny and fast. If you need similar services on Linux or Windows consider imagemagick.
